### ISSUE TITLE
エフェクト

### ISSUE THREAD

**Issue by nakamoto02** [nkc-saitou/CatchTheBall#8]
必要
- 花火玉の爆発(クリア時)
- 花火玉の爆発(ゲームオーバー時)
- 花火玉発射時(マズルフラッシュ)
- 花火玉の速度確認用
- プレイヤーの操作が移った時
- 撃った後のキャラの爆発
- 土埃(プレイヤー移動時)
- ジャンプ(プレイヤー)

**Comment by matsumoto36** [comment]
以下のエフェクトを実装しました

- 花火の爆発(クリア時)
- 花火の爆発(ゲームオーバー時)
- 花火の速度確認用Lv1
- 花火の速度確認用Lv2
- 花火の速度確認用Lv3
- クリア時の花火のトレイル
- プレイヤー1が乗り移ったとき
- プレイヤー2が乗り移ったとき
- プレイヤー3が乗り移ったとき
- プレイヤー4が乗り移ったとき
- プレイヤーが死んだとき
- プレイヤーが動いたとき
- プレイヤーがジャンプしたとき
- 撃った時の火炎
